# Generated by Django 3.1.6 on 2021-03-07 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDatabase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voting_number', models.TextField()),
                ('user_img', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
