# Generated by Django 3.1.6 on 2021-03-07 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210307_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='city',
            field=models.CharField(default=None, max_length=15),
        ),
        migrations.AlterField(
            model_name='voter',
            name='district',
            field=models.CharField(default=None, max_length=15),
        ),
        migrations.AlterField(
            model_name='voter',
            name='fname',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='voter',
            name='lname',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='voter',
            name='mname',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='voter',
            name='state',
            field=models.CharField(default=None, max_length=15),
        ),
        migrations.AlterField(
            model_name='voter',
            name='taluka',
            field=models.CharField(default=None, max_length=15),
        ),
        migrations.AlterField(
            model_name='voter',
            name='village',
            field=models.CharField(default=None, max_length=15),
        ),
        migrations.AlterField(
            model_name='voter',
            name='voting_number',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
