# Generated by Django 3.1.6 on 2021-03-07 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210307_2116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voter',
            name='id',
        ),
        migrations.AlterField(
            model_name='voter',
            name='voting_number',
            field=models.CharField(default=None, max_length=20, primary_key=True, serialize=False),
        ),
    ]
