# Generated by Django 3.1.6 on 2021-03-07 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210307_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='address',
            field=models.TextField(default=None),
        ),
    ]
