# Generated by Django 3.1.6 on 2021-03-08 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_voter_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='dob',
            field=models.DateField(default=None),
        ),
    ]
