# Generated by Django 3.1.6 on 2021-04-06 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210406_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='user_img',
            field=models.ImageField(default=None, upload_to='voters/'),
        ),
    ]
