# Generated by Django 3.2 on 2021-04-07 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20210406_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='user_img',
            field=models.ImageField(default=None, upload_to='images/voters/'),
        ),
    ]
