# Generated by Django 3.2 on 2021-04-09 02:52

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_voter_user_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='voted_elections',
            field=django_mysql.models.ListTextField(models.IntegerField(), default=None, size=1000),
        ),
    ]
