# Generated by Django 3.2 on 2021-04-09 03:35

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_voter_voted_elections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='voted_elections',
            field=django_mysql.models.ListTextField(models.IntegerField(), blank=True, default=[], size=1000),
        ),
    ]
