# Generated by Django 3.1.6 on 2021-03-29 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_election', models.CharField(default=None, max_length=30)),
                ('name_of_election', models.CharField(default=None, max_length=30)),
                ('state', models.CharField(default=None, max_length=30)),
                ('district', models.CharField(default=None, max_length=30)),
                ('taluka', models.CharField(default=None, max_length=30)),
                ('city', models.CharField(default=None, max_length=30)),
                ('village', models.CharField(default=None, max_length=30)),
                ('starting_time', models.TimeField()),
                ('ending_time', models.TimeField()),
                ('date', models.DateField(default=None)),
                ('hold', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
