# Generated by Django 3.1.6 on 2021-03-29 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='name_of_election',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
