# Generated by Django 3.2 on 2021-04-07 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0002_auto_20210329_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
