# Generated by Django 3.2 on 2021-04-09 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0003_alter_election_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='NOTA_votes',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
