# Generated by Django 3.2 on 2021-04-10 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0004_election_nota_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='isOver',
            field=models.BooleanField(default=False),
        ),
    ]
