# Generated by Django 3.2 on 2021-04-10 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0010_alter_candidate_total_votes'),
        ('election', '0006_election_election_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='election_winner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='candidate.candidate'),
        ),
    ]
