# Generated by Django 3.1.6 on 2021-04-06 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_id', models.CharField(default=None, max_length=30)),
                ('election_id', models.CharField(default=None, max_length=30)),
                ('party_name', models.CharField(default=None, max_length=30)),
                ('party_logo', models.ImageField(default=None, upload_to='images/candidates')),
                ('party_motto', models.TextField(default=None, max_length=200)),
                ('party_leader', models.CharField(default=None, max_length=30)),
                ('total_votes', models.PositiveBigIntegerField()),
            ],
        ),
    ]
