# Generated by Django 3.2 on 2021-04-07 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0003_auto_20210406_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='party_logo',
            field=models.ImageField(upload_to='images/candidates/'),
        ),
    ]
