# Generated by Django 3.2 on 2021-04-08 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_voter_user_img'),
        ('candidate', '0008_alter_candidate_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='voter_id',
        ),
        migrations.AddField(
            model_name='candidate',
            name='voter',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.voter'),
        ),
    ]
