# Generated by Django 3.2 on 2021-04-09 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0009_auto_20210408_0746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='total_votes',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
