# Generated by Django 3.2 on 2021-04-10 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0012_remove_election_election_winner'),
        ('candidate', '0010_alter_candidate_total_votes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='election_id',
        ),
        migrations.AddField(
            model_name='candidate',
            name='election',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='election.election'),
        ),
    ]
